# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-02 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pubilshed_date',
            new_name='published_date',
        ),
    ]
